### ISSUE TITLE
Cool API

### ISSUE THREAD

**Issue by Todd-Werelius** [cubehouse/wdwJS#1]
Nice API, couple of questions

I was browsing the code and saw that under some circumstances mapping information might be provided, but playing with the API I have never seen any such information passed back in the json data, is there some way to request this in the API or ... ?

Do you know of anyway to get back information other than attractions and entertainment, like dining, shops, restrooms etc? 

Anyway, saved me some time from porting the echelon source from ruby, so double thanks for that!

**Comment by cubehouse** [comment]
Heya,

All the this.[whatever] functions in disneyRequest.js are available to use
in the API.

So you can use api.GetPage(id, type, callback);

Protip: see all members of an object: for(var key in api) console.log(key +
": " + typeof(api[key]));

You'll have to play with the api yourself to find the right page types and
IDs. I plan to add more helper functions for ease of access later, but this
should get you that you need.

I'm on holiday atm (...... Guess where?.....) so I can't get to my API
notes for a sample right now. Let me know how you get on and I'll see what
I can find later in the week if you can't make any progress.

All the best.

**Comment by Todd-Werelius** [comment]
Thanks, already started experimenting, let you know what I find

Yeah just got back myself from Disneyland last week, have a good time!

**Comment by cubehouse** [comment]
Heya,
Sorry for the delay. Back from Disney World now! (with a cold and jet lag).

Feel free to make pull requests if you have any improvements to suggest. That will be very exciting for me to get :)

I'll look into adding more convenient methods for things outside of just wait times soon, and add to the documentation to explain how to make generic API requests in case a helper function doesn't exist.

**Comment by Todd-Werelius** [comment]
Been working on it, quite a lot of info is available, very interesting when I get some time I will do a pull

**Comment by cubehouse** [comment]
Disneyland and CaliforniaAdventure have been added in v0.1.4 (didn't get any pull requests, so added it in last week).

Nothing left to do on this issue.
