### ISSUE TITLE
Disneyland Paris rides schedule

### ISSUE THREAD

**Issue by PhilippeP62** [cubehouse/wdwJS#10]
Rides Opening times seems to be on GMT ... 
All rides have an offset of 1 hour with parks times ...

**Comment by cubehouse** [comment]
This sounds correct to me?
Times when in GMT should be an hour behind Paris. You'll need to use a timezone aware library such as momentjs to handle times.

**Comment by PhilippeP62** [comment]
In DisneyRequest do you not allready use momentjs ...
I thought the times would come out as local time...
So Paris time for DLP , Orlando time for WDW ...

2016-01-17 16:02 GMT+01:00 James Holding <notifications@github.com>:

**Comment by cubehouse** [comment]
This is something I actually support in the new refactor of the project.

But are you saying that the times are incorrect? Because it's returning 09:00 GMT, which is 10:00 in Paris time which is correct?

**Comment by PhilippeP62** [comment]
The times are correct if GMT ...
It seemed more natural to return times on local timezone.

2016-01-17 18:52 GMT+01:00 James Holding <notifications@github.com>:

**Comment by cubehouse** [comment]
OK, this is a feature request, which is being met in version 3 of the API. So closing for now.

Will be available soon :)

**Comment by cubehouse** [comment]
3.0.0 is now available and returns times in local timezone.
Can override with "timeFormatTimezone"
