### ISSUE TITLE
Ride OpeningTime and ClosingTime lost in v3.0

### ISSUE THREAD

**Issue by jeanmatthieud** [cubehouse/wdwJS#13]
Hi,

Since v3, the response to GetWaitTimes(), doesn't include opening time and closing time of each ride anymore (tested with disneylandparis)

Is it possible to restore this functionality ?

Thanks

**Comment by cubehouse** [comment]
Back in v2 of the library, we were using an old version of the Disneyland Paris API which is no longer used or updated by Disney sadly.

They now use the same API servers and setup as the Florida/California parks, which probably offer ride opening times but I'm not sure where that data is yet. We can try and find that and add it if it's in there, I can give it a poke over the weekend if I get a spare moment.

**Comment by jeanmatthieud** [comment]
Could be great ! Thanks !

**Comment by cubehouse** [comment]
See PR #15 for work on this (combined with some work for issue #14).

Hopefully have most of this work done today, just need to watch some of the park APIs during operating hours to confirm how they behave when rides are down for maintenance etc.

**Comment by cubehouse** [comment]
Added ride schedule data to Disney parks in 3.0.6, which is on npm now.

**Comment by jeanmatthieud** [comment]
Great !
