### ISSUE TITLE
WeakMap is missing from the dependencies 

### ISSUE THREAD

**Issue by PhilippeP62** [cubehouse/wdwJS#3]
I'm quite new to Node.js so I'm a bit lost 
In several scripts new WeakMap is called but is not in the dependencies of astify (it seems that it is astify that needs it.) 
Do i just install WeakMap from anywhere , or do I have to be in the astify folder ?

Thanks
Philippe

**Comment by cubehouse** [comment]
I've tested the module on Windows and Linux. What version of Node.JS are you using? And what platform are you on?

Also are you using the module from npm (what version have you got from npm), or have you pulled this yourself from GitHub?

Thanks

**Comment by PhilippeP62** [comment]
I'm running Node.js on my Synology NAS.(it might be quite old -10.36)
I've installed it from npm using npm install wdwjs@2.0.1 --save

**Comment by cubehouse** [comment]
That is quite out-of-date, I test against 4.x and 5.x.
You can just install WeakMap wherever you like in your project. Install it as part of your own codebase and the astify module should still find it.
I'm going to setup a test on v0.10.x now, but can you try running 'npm install weakmap --save' in your own project and see if that fixes it? Then I can look into when this appeared in NodeJS and add weakmap as a dependency for older versions.

**Comment by PhilippeP62** [comment]
installing weakmap doesn't solve the problem , but don't bother , my nodejs is too old , I'll use a rasperry pi and install a recent version.
I used the NAS because it is allways on.

Thanks 
Philippe

**Comment by cubehouse** [comment]
I want to support as many people as possible, so I'm pushing out a fix now!
Tested with 0.10.41 successfully. Was mainly an error with astify, which I use for some HTML parsing. It's actually a fork of somebody else's repo on GitHub, but it was never put on npm, so I guess I'm maintaining it at the moment!

2.0.3 now on npm with fix :)

**Comment by PhilippeP62** [comment]
It's now working on my NAS also ! Thanks

**Comment by cubehouse** [comment]
Brilliant! Glad to hear :)
I'm now running automated tests on a ton of different node versions, so I'm hoping I can maintain 0.10 compatibility. I don't plan on using any odd recent language features anyway!
