### ISSUE TITLE
TypeError in DisneyBase.js

### ISSUE THREAD

**Issue by jeanmatthieud** [cubehouse/wdwJS#32]
I've received an error of one of my app using wdwjs (3.1.3):
```
TypeError: Cannot set property 'correlation' of null
  File "/opt/attractions/attractions-task-wdwjs/node_modules/wdwjs/Disney/DisneyBase.js", line 476, in null.<anonymous>
    self._accessToken.correlation = resp.headers["x-correlation-id"];
  File "/opt/attractions/attractions-task-wdwjs/node_modules/wdwjs/parkBase.js", line 174, in Request._callback
    return callback(err, resp, body);
```

I did not analyse this bug, but a check seems mandatory on _accessToken or before.

**Comment by cubehouse** [comment]
Sorry for the delay in getting back to you!
I've been in overtime at my day job, so finally getting around to sorting things like this!

Added a check to make sure that line won't be hit if _accessToken is somehow not defined. Think this is a weird unlucky timing issue.

Did this happen just the once?

I'll push out an update shortly with the fix.
