### ISSUE TITLE
Europa-Park API

### ISSUE THREAD

**Issue by Meteorus** [cubehouse/wdwJS#34]
Hi,

since the last update of the offical Europa-Park app, wdwJS does not longer work. I get always the following error:

`[ERROR :: Europa-Park]  Failed to parse JSON data from Europa API SyntaxError: Unexpected token < in JSON at position 0:
You are not authorized to view this page
The Web server you are attempting to reach has a list of IP addresses that are not allowed to access the Web site, and the IP address of your browsing computer is on this list.
Please try the following:
Contact the Web site administrator if you believe you should be able to view this directory or page.
HTTP Error 403.6 - Forbidden: IP address of the client      has been rejected.<br>Internet Information Services (IIS)
Technical Information (for support personnel)
Go to Microsoft Product Support Services and perform a title search for the wordsHTTP and 403.
Open IIS Help, which is accessible in IIS Manager (inetmgr),
 and search for topics titled About Security, Limiting Access by IP Address, IP Address Access Restrictions, and About Custom Error Messages.
Failed to parse JSON data from Europa API`

I've found out, that they have changed the API URL. Because the new App works fine outside off the park with a faked GPS coordinate.

I hope there will be an update that fix that issue.
Thank you a lot!

**Comment by cubehouse** [comment]
Hi @	Meteorus!

Thank you for your issue report, I've update the codebase to support the new API.

You luckily caught me on a quiet Sunday afternoon, don't expect this kind of fast turnaround normally! :)
Grab 3.1.7 or the latest source to get the updates.

Thanks!

**Comment by Meteorus** [comment]
Hi @cubehouse

Thank your, really, really much! I didn't expected a fix in this short time!
