### ISSUE TITLE
Info api

### ISSUE THREAD

**Issue by elstringer** [cubehouse/wdwJS#35]
Is it possible to recover from api list of all attractions the park ( although it is not Waiting time example of the list using Europapark is not complete)

Can recover your url from a miniature picture of the attractions ?

And the restaurant list
And the shops ?

Can also retrieve your rate peak of the park?

Recover rates from api

Adding walibi park

**Comment by cubehouse** [comment]
Hi,

I'm sorry but I don't completely understand the issue you're describing with this ticket.

If this is for multiple feature requests, can you please write them up separately with implementation details so I can understand what you're after.

We can attempt to add restaurants and shops etc. but again, please make a separate request with some implementation suggestions (ideally a pull request if possible) to start a conversation about this going.

If you want ride peak times etc. you'll have to do this yourself, as this requires collecting data over time, which is way beyond the scope of this project to merely fetch the waiting times when requested.

I'm not sure what Walibi Park is, you can supply us an implementation yourself if you wish, or supply some details about where the wait times for this park are available so they can be added in a separate issue. If there are no official wait times available anywhere, we won't be able to support that park.

Thanks
