### ISSUE TITLE
shanghai disneyland sometimes not return full information

### ISSUE THREAD

**Issue by laumik** [cubehouse/wdwJS#37]
Hi,
Thank you guys for wdwJS project. I have installed it on heroku free account. I am using wdwJS for my ios app that can show Shanghai Disneyland wait times.
But when I access it with my app, it does not always get all attractions (36 attractions), sometimes it just return some attractions, maybe 12 or 20 attractions. I have tried hundreds times, still not figure out what was wrong? 
my data url:
https://murmuring-reaches-12907.herokuapp.com/SH

**Comment by cubehouse** [comment]
Are you calling the GetWaitTimes every time you access that URL?
You should probably look into caching the data so you aren't always fetching it with every API hit.

I'll look into this later though to see if/why it's being inconsistent.

**Comment by laumik** [comment]
yes, every time. I know it needs cache to be more efficient. but not do that yet when my app is just in testing run.
and another question, there are Disney official apps for wait times, maybe someday disney will close its official go.com api and stop wdwJS?
is this disney official api?
https://api.wdpro.disney.go.com/facility-service/

**Comment by cubehouse** [comment]
Yes, this could stop working at any point for any park.

**Comment by laumik** [comment]
just curious, how did you find this go.com api?

**Comment by PhilippeP62** [comment]
but currently, the official Disney apps rely on those apis.

2016-09-01 15:51 GMT+02:00 James Holding <notifications@github.com>:

**Comment by cubehouse** [comment]
I cannot explain this I'm afraid, I really have no control over other people's APIs.

However, the best approach is to be caching these results and returning the cached versions. You want a list of rides with the last wait times, which you can update when you get new data. This way, even if you don't get any data for a ride once or twice, you'll still have the recent previous data to fallback on.

I'm closing this issue now, as I fear there isn't anything this library can do to change the behavior of external APIs.
