### ISSUE TITLE
Add SeaWorld/BuschGardens

### ISSUE THREAD

**Issue by cubehouse** [cubehouse/wdwJS#4]
Add additional SeaWorld Florida parks to the API.

Can look at the ruby implementation listed in project acknowledgments, but I'm unsure if it is still functional.

**Comment by PhilippeP62** [comment]
I just saw that Hong Kong Disneyland has joined the Disney Parks Website Family , so probably the same API ...

**Comment by cubehouse** [comment]
If this is so, can you create a new issue with some links and I'll have a look when I get some time! Would love to get HK on here.

**Comment by cubehouse** [comment]
Added SeaWorld (and Busch Gardens) parks in c245b059b629203da21c495edfc46d1c39588ce3

Will be in 3.0.0, part of the refactor in PR #7 

Closing now, as will be available very soon
