### ISSUE TITLE
Disneyland Shanghai 

### ISSUE THREAD

**Issue by PhilippeP62** [cubehouse/wdwJS#8]
...has updated its website and guess what :)

This might be the first park to get data access since opening day !

**Comment by cubehouse** [comment]
haha... you seem to be endlessly watching all the Disney websites!

resort_id: shdr
park: desShanghaiDisneyland

No data is available yet for wait times, schedules etc (not surprisingly!)

Will have to check again closer to the opening day!

**Comment by PhilippeP62** [comment]
Well the announcement of the opening day , triggered the updated website , my main interest still is Disneyland Paris which is the closest for me ... :)

**Comment by cubehouse** [comment]
Added to API ready for opening day!
